### ISSUE TITLE
Server errors when archiving pages or viewing history tab

### ISSUE THREAD

**Issue by LABCAT** [silvershop/silverstripe-hasonefield#14]
If my Page has a HasOneButtonField I get the following error when I archive a page or view the history tab:

[Emergency] Uncaught BadMethodCallException: Object->__call(): the method 'forTemplate' does not exist on 'VideoHolder'

I can get around this error using the following:
```
$controller = Controller::curr();
 if (!$this->isArchived() && !$controller instanceof CMSPageHistoryController) {

}
```

Is there a better way to accomplish this?

**Comment by wilr** [comment]
@LABCAT can you provide the versions of Framework and the picker you used. Was this SilverStripe 4?
