### ISSUE TITLE
Removing autocomplete if not required

### ISSUE THREAD

**Issue by simonwinter** [silvershop/silverstripe-hasonefield#25]
Hi there,

We're using the module with this SilverStripe Link Module (https://github.com/gorriecoe/silverstripe-linkfield)

The autocomplete gets in the road of the user experience a little. In this case, I'd like users to click add new so they are required to fill out a form before saving to the relation.

Is there anyway we could pass in some sort of config to enable/disable the autocomplete?

![image](https://user-images.githubusercontent.com/1104537/48233364-c7129800-e419-11e8-8b07-1c9a343ee7e4.png)

**Comment by wilr** [comment]
@simonwinter You can try remove the component after you create the field.

`$hasOneField->getConfig()->removeComponentsByType(HasOneAddExistingAutoCompleter::classs);`

If you want to make a shortcut for this (e.g $hasOneField->setShowAutocomplete(false)` happy to accept PRs

**Comment by simonwinter** [comment]
Thanks @wilr!

**Comment by thats4shaw** [comment]
Curious whether this approach worked for you @simonwinter?  I attempted to do the same thing and then stumbled across this issue.
