### ISSUE TITLE
Broken templates

### ISSUE THREAD

**Issue by sanderha** [silvershop/silverstripe-hasonefield#28]
When using the field, it got rendered like this:

![image](https://user-images.githubusercontent.com/6941043/50221864-d2e96680-0396-11e9-97a5-3b39fccf6d02.png)

adding "stacked" in the template solved this issue to:

![image](https://user-images.githubusercontent.com/6941043/50221882-e268af80-0396-11e9-8b3f-db0a91315bcb.png)

**Comment by sanderha** [comment]
#27

**Comment by mooror** [comment]
@wilr Can you please create a new release that includes the fix from #27? I just attempted to use the module with 4.3 and I can confirm that this is still an issue.

Thanks in advance, 
Mooror

**Comment by wilr** [comment]
Tagged `3.0.1`
