### ISSUE TITLE
$fixture_file should be protect in tests

### ISSUE THREAD

**Issue by rafaeldsousa** [silvershop/silverstripe-hasonefield#30]
Just ran into this, when trying to run `vendor/bin/phpunit` we have the following error

`Fatal error: Access level to SilverShop\HasOneField\Tests\HasOneButtonFieldTest::$fixture_file must be protected (as in class SilverStripe\Dev\SapphireTest) or weaker in /Users/rafael.desousa/Sites/mcdem4/vendor/silvershop/silverstripe-hasonefield/tests/HasOneButtonFieldTest.php on line 15`

updating $fixture_file to protected seems to do the trick. 

Using v3.0.1

**Comment by wilr** [comment]
@rafaeldsousa it's protected in the dev-master branch. I've just tagged a 3.0.2 stable which fixes this
