### ISSUE TITLE
Feature Request: Filter autocompleted results

### ISSUE THREAD

**Issue by davejtoews** [silvershop/silverstripe-hasonefield#40]
I'd like to be able to use this field on a relationship where only a certain subset of objects which have the related class are available in the autocompleted.

My particular use case is using the `silverstripe/taxonomy` module. I've I've got a $has_one taxonomy term relationship but want to limit it to terms of type "Category" I can do the following with a DropdownField

```
DropdownField::create(
    'CategoryID',
     'Category',
     TaxonomyTerm::get()->filter(['Type.Name:ExactMatch' => 'Category'])
 )
```

I'd love to be able to pass a DataList directly to this field, rather than have it grab everything of the related class.

I may eventually get time to submit a PR for this, but would appreciate feedback on implementation. The `__construct` method already takes a lot of arguments. Another could be added if we want a non-breaking change, but it might make more sense to move some of this to additional methods?

**Comment by mlewis-everley** [comment]
@davejtoews This should be possible via the base gridfield's `GridFieldAddExistingAutocompleter::setSearchList()`.

Something like this should do the trick:

```
$property = HasOneButtonField::create(
    $this,
    'Property'
);

$property
    ->getConfig()
    ->getComponentByType(HasOneAddExistingAutoCompleter::class)
    ->setSearchList($locations);

$fields->addFieldToTab(
    'Root.Main',
    $property
);
```

**Comment by wilr** [comment]
@davejtoews if the above works for you then I'll close this issue. Could just add this to the README

**Comment by davejtoews** [comment]
@wilr Yeah that works. A note in the README would be great. Thanks.
