### ISSUE TITLE
Not so much an Issue, But question ...

### ISSUE THREAD

**Issue by lexandclo** [silvershop/silverstripe-hasonefield#66]
Hi
Whats the best way to change the $summaryField on the readonly display? As it is, it reads the title and i would like it to read another field.
Ive tried setSummaryField in both the dataobject that has the hasoneField and the dataobject that its linked too, but it doesnt change.
If i change in the core files it works. Is it a case of an extension or is there another way?
Thanks
Darren

**Comment by mooror** [comment]
Hey there Lex (@lexandclo ), 

I know this is a bit of a late reply, but to answer your question, you need to access the `GridFieldSummaryField` component and call it's `setSummaryField()` method in order to change the field used for the read only display

Here's a working example (tested on SS 4.10):
```php
// Place this at the top of your php class
use SilverShop\HasOneField\GridFieldSummaryField;

// Use this code wherever you are using the HasOneButtonField (`getCMSFields()`, Form, etc.)
$hasOneField = HasOneButtonField::create(
    // Your configuration goes here...
);

// Changes the readonly field
$hasOneFieldConfig = $hasOneField->getConfig();
$hasOneSummaryComponent = $hasOneFieldConfig->getComponentByType(GridFieldSummaryField::class);
$hasOneSummaryComponent->setSummaryField("CustomField"); // Replace "CustomField" with the field you want to use
```

**Comment by mooror** [comment]
@wilr Unless Lex ends up having other issues, I think this issue can be closed

**Comment by wilr** [comment]
@mooror thanks
