### ISSUE TITLE
Doesn't work with (Data)Extensions (Fixed)

### ISSUE THREAD

**Issue by gameplay4all** [silvershop/silverstripe-hasonefield#7]
Hey, 

Just signed up to github just for this, so this is probably in the wrong place but:
The HasOneButtonField throws an error when used on a (Data)Extension in the updateCMSFields function.

I fixed it so you can add to HasOneButtonField on line 11
`
if( is_subclass_of($parent, 'Extension')  )
            $this->record = $parent->getOwner()->{$name}();
        else
            $this->record = $parent->{$name}();
`

**Comment by mi3ll** [comment]
Hello @gameplay4all,

You should be able to fix this in your updateCMSFields by adding **$this->owner instead of $this** as the third parameter on the HasOneButtonField. See example below.

```
    HasOneButtonField::create("Address", "Address", $this->owner);
```
