### ISSUE TITLE
SilverStripe\Forms\GridField\GridField not found

### ISSUE THREAD

**Issue by Jeremuelle** [silvershop/silverstripe-hasonefield#9]
Hi, I'm using SS 3.6 and I got the error below, any clue?

` Class 'SilverStripe\Forms\GridField\GridField' not found in /Applications/MAMP/htdocs/NEDC/public/hasonefield/code/HasOneButtonField.php on line 13`

**Comment by wilr** [comment]
Please use the `1.0.0` tag
